dataset: "Bulgarian"

mfa:
  base_dictionary_model: "bulgarian_mfa"
  alignment_dictionary: "lexicon/bulgarian_mfa_runtime.dict"
  acoustic_model: "bulgarian_mfa"
  g2p_model: "bulgarian_mfa"
  max_failed_ratio: 0.01

path:
  corpus_path: "bg_realdata"
  manifest_path: "bg_realdata/manifest.csv"
  runtime_lexicon_path: "lexicon/bulgarian_mfa_runtime.dict"

  raw_path: "./raw_data/Bulgarian"
  preprocessed_path: "./preprocessed_data/Bulgarian"

preprocessing:
  val_size: 500
  split_seed: 42
  clean_output: True
  prune_raw_output: True
  max_rejected_ratio: 0.01
  max_feature_rejected_ratio: 0.01
  text:
    text_cleaners: ["bulgarian_cleaners"]
    language: "bg"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
